### ISSUE TITLE
Floating repeating events

### ISSUE THREAD

**Issue by arnim279** [sebbo2002/ical-generator#442]
There are some problems with floating, repeating events.
Currently, a floating, repeating event looks like this:
```ical
BEGIN:VEVENT
...
DTSTART:20221125T082500
DTEND:20221125T091000
RRULE:FREQ=WEEKLY;UNTIL=20230726T082500Z
EXDATE:20230224T082500Z,20230106T082500Z
SUMMARY:Event Title
END:VEVENT
```
As you can see, the `DTSTART` and `DTEND` datetimes are 'floating', so they don't end with the `Z` UTC time zone specifier.
The `RRULE:UNTIL` and `EXDATE` properties however are still treated as UTC datetimes. In my case, the `RRULE:UNTIL` property is not affected, but I imagine in some edge cases it could be. My main issue is with the excluded dates. To properly exclude an event from the recurrence set, the excluded time must match the `DTSTART` time. This does not work if that time is 'floating'.

[This](https://github.com/sebbo2002/ical-generator/blob/b19e94bdc9408acfb6e64d93de614ad25edb4ad0/src/event.ts#L1536-L1538) is the affected code (the `dateonly` and `floating` parameters to `formatDate()` are always undefined).

The solution would be to 
- allow floating excluded datetimes or to
- allow specifying excluded dates (`EXDATE;VALUE=DATE=[list of date]`)

I might be wrong about the details however, I don't have a lot of experience in working with ICal.

**Comment by arnim279** [comment]
Oh, and another problem I just noticed: when I pass `2022-11-25T09:25:00` as the start datetime to a 'floating' event, the date time always gets converted to UTC, so in this case the `DTSTART` is `20221125T082500` which is an hour earlier than it's meant to be.

**Comment by sebbo2002** [comment]
Sorry for the late reply, had a cold in between and only now got to look through the GitHub notifications. 

As I see it, this is a bug, since both `UNTIL` and `EXDATE` should contain floating dates. Am I seeing this correctly?

**Comment by arnim279** [comment]
No worries for taking a bit longer, I hope you're better now!

Based on my knowledge of iCal I do think that your library should support floating `UNTIL` and `EXDATE` properties, since the following file works as I expected when imported into Apple Calendar.

```ical
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//arnim279/demo
BEGIN:VEVENT
SUMMARY:Test Event
UID:1
DTSTAMP:20221206T120000
DTSTART:20221206T120000
DTEND:20221206T130000
RRULE:FREQ=WEEKLY;COUNT=4
EXDATE:20221213T120000
END:VEVENT
END:VCALENDAR
```

I am however pretty unsure whether this is the behavior intended in the iCal RFC, because I can't find any mention of floating `EXDATE` values in the sections for [date-time values](https://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html) or [for exdates](https://icalendar.org/iCalendar-RFC-5545/3-8-5-1-exception-date-times.html).
I'll try to see if I can find out more, I want to make sure this behavior is even compliant with the standard before asking for a change.

**Comment by sebbo2002** [comment]
> I'll try to see if I can find out more, I want to make sure this behavior is even compliant with the standard before asking for a change.

Have you been able to find out anything in the meantime? I haven't so far, to be honest.

**Comment by arnim279** [comment]
I haven't found anything either, but because both the [icalendar validator](https://icalendar.org/validator.html) and Apple Calendar accept my example I guess it's fine?

**Comment by sebbo2002** [comment]
I would also just assume that it is. If it is wrong and it breaks on a client, hopefully someone will report in the issues.

I would take care of an implementation if it is not urgent for you. But it can happen in the new year, I can not currently estimate when I come to it. Because of the holidays etc.

**Comment by sebbo2002** [comment]
@arnim279  I released a pre-release with the change. Can you check if it's now fixed for you? You can install the latest pre-release with `npm i ical-generator@next`.

**Comment by arnim279** [comment]
It still doesn't quite work. Your library still adds the `Z` specifier to exdates, so the code
```ts
import ical from "ical-generator";

let c = new ical.ICalCalendar();

c.createEvent({
	summary: "test event",
	start: "2022-12-20T20:00:00Z",
	end: "2022-12-20T21:00:00Z",
	repeating: {
		freq: ical.ICalEventRepeatingFreq.DAILY,
		count: 7,
		exclude: ["2022-12-21T20:00:00Z", "2022-12-23T20:00:00Z"],
	},
	floating: true,
});

console.log(c.toString());
```
generates the calendar
```ical
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//sebbo.net//ical-generator//EN
BEGIN:VEVENT
UID:97773932-60c9-439f-a587-30a00743e86f
SEQUENCE:0
DTSTAMP:20221220T203338Z
DTSTART:20221220T200000
DTEND:20221220T210000
RRULE:FREQ=DAILY;COUNT=7
EXDATE:20221221T200000Z,20221223T200000Z <- still includes 'Z'
SUMMARY:test event
END:VEVENT
END:VCALENDAR
```
The native iOS Calendar app still excludes those two recurrences, but I also tested it with Google Calendar and there the exdates are only accepted **without** the `Z` UTC specifier.

But at a first glance, [the changes](https://github.com/sebbo2002/ical-generator/pull/448/files#diff-ae46631882b9ce2507fe0bd58d434f6701fa5ad8482399d43047461f2d3789a2R1537) you made in the prerelease make sense, so I'm not quite sure why it's still included.
Thanks for the quick implementation by the way!

**Comment by arnim279** [comment]
Yup, it works now! Thanks for the quick implementation :D
